//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileHasher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileHasher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string BrowseButtonDefaultText {
            get {
                return ResourceManager.GetString("BrowseButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        internal static string CompareButtonDefaultText {
            get {
                return ResourceManager.GetString("CompareButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        internal static string ComputeButtonDefaultText {
            get {
                return ResourceManager.GetString("ComputeButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyButtonDefaultText {
            get {
                return ResourceManager.GetString("CopyButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected..
        /// </summary>
        internal static string FilenameTextBoxDefaultText {
            get {
                return ResourceManager.GetString("FilenameTextBoxDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file..
        /// </summary>
        internal static string FileSaveErrorText {
            get {
                return ResourceManager.GetString("FileSaveErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1.
        /// </summary>
        internal static string Group1Header {
            get {
                return ResourceManager.GetString("Group1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you wish to calculate the checksum for..
        /// </summary>
        internal static string Group1Label {
            get {
                return ResourceManager.GetString("Group1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2.
        /// </summary>
        internal static string Group2Header {
            get {
                return ResourceManager.GetString("Group2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute the checksum for the selected file..
        /// </summary>
        internal static string Group2Label {
            get {
                return ResourceManager.GetString("Group2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3.
        /// </summary>
        internal static string Group3Header {
            get {
                return ResourceManager.GetString("Group3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare the generated checksum to the one supplied for the file or export the checksum for other uses..
        /// </summary>
        internal static string Group3Label {
            get {
                return ResourceManager.GetString("Group3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid file name..
        /// </summary>
        internal static string InvalidFilenameErrorText {
            get {
                return ResourceManager.GetString("InvalidFilenameErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButtonDefaultText {
            get {
                return ResourceManager.GetString("SaveButtonDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Checksum.
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
    }
}
